config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:show, :new, :create] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save!
      redirect_to @cocktail
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to @cocktail
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1 class="text-white text-center m-5 font-weight-bold">Cocktails</h1>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-4">
      <div class="card mb-5 shadow rounded">
        <% if cocktail.photo.attached? %>
          <%= cl_image_tag cocktail.photo.key, class: "cocktail-pic"%>
        <% end %>
        <div class="card-body">
          <h5 class="card-title font-weight-bold"><%= cocktail.name %></h5>
          <%= link_to "See details", cocktail, class: "btn btn-outline-success badge-pill" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1 class="text-white text-center font-weight-bold m-4">Create a Cocktail</h1>
<div class="container w-50 vh-100 text-white">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Create!", class: "btn btn-outline-success btn-block" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-4">
      <h1 class="d-flex justify-content-between text-white mt-3 mb-3 font-weight-bold">
        <%= @cocktail.name %>
        <%# link_to icon('fas', 'plus', class: 'strong text-success'), new_cocktail_dose_path(@cocktail) %>
      </h1>
      <ul class="list-group list-group-flush">
        <% @cocktail.doses.each do |dose| %>
          <li class="list-group-item bg-transparent text-white h4">
            <%= dose.ingredient.name %> - <%= dose.description %> 
            <%= link_to icon('far', 'trash-alt', class: 'strong text-success'), dose, method: :delete, data: { confirm: "Are you sure?" } %>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="col-2 text-white">
      <h2 class="mt-3 mb-3 pt-1 pb-1">Add a dose</h2>
      <%= simple_form_for [ @cocktail, @dose ] do |f| %>
        <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
        <%= f.input :description %> 
        <%= f.submit "Mix!", class: "btn btn-outline-success badge-pill text-center btn-block" %>
      <% end %>
    </div>

    <div class="col-6">
    
      <% if @cocktail.photo.attached? %>
        <%= cl_image_tag @cocktail.photo.key, class: "cocktail-img" %>
      <% else %>
        There is no image
      <% end %>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container text-white">
  <h1 class="mt-5">Create a new dose</h1>

  <%= simple_form_for [ @cocktail, @dose ] do |f| %>
    <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
    <%= f.input :description %> 
    <%= f.submit "Mix!", class: "btn btn-outline-success badge-pill text-center" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-transparent position-sticky fixed-top">
  <%# <i class="fas fa-cocktail"></i> %>
  <h1><%= link_to icon("fas", "cocktail"), root_path, class: "text-success strong" %></h1>
  <%= link_to "Create a Cocktail", new_cocktail_path, class: "btn btn-outline-success my-2 my-sm-0 badge-pill" %>

  <%# <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form> %>
</nav>